on:
  pull_request:
    branches:
      - main
jobs:
  auto-merge:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.mytoken }}
